public class ZeroBounceResponse {
    public String address;
    public String status;
    public String sub_status;
    public String free_email;
    public String did_you_mean;
    public String account;
    public String domain;
    public String domain_age_days;
    public String smtp_provider;
    public String mx_record;
    public String mx_found;
    public String firstname;
    public String lastname;
    public String gender;
    public String country;
    public String region;
    public String city;
    public String zipcode;
    public String processed_at;
}